### ISSUE TITLE
Build DACPAC with references

### ISSUE THREAD

**Issue by jmezach** [microsoft/DacFx#124]
At the moment it seems that it is not possible to build a dacpac that references objects in other dacpac packages, or I just can't figure out how to do it. Is this something that's planned to be added?

**Comment by Coder3333** [comment]
@jmezach , did you ever figure this out?  If you right click References on the project from Visual Studio and then select "Add Database Reference", it brings up a screen where you can select another dacpac to reference.

**Comment by Adam-S-Daniel** [comment]
I suggest renaming this issue to correspond to this ticket on Developer Community: [“On Roadmap” since 2020: _NuGet database references in SSDT database projects_](https://developercommunity.visualstudio.com/t/nuget-database-references-in-ssdt-database-project/785063). I agree with @Coder3333 that the current name implies a feature that already exists: direct references to DacPac files, akin to the bad old days when one might add a reference to a DLL as opposed to achieving the same through a NuGet dependency.

@dzsquared, might it make sense for your team to reach out to [@nkolev](https://github.com/nkolev92) for the NuGet team’s thinking/guidance on this?
https://github.com/NuGet/Home/issues/545#issuecomment-1245941067
> Team Triage:
> 
> The work that would be required here needs to be done by a different component, the SQL server Database Tools projects and not NuGet.
> 
> Please upvote and follow the following issue in the DacFx repo, [microsoft/DacFx#124](https://github.com/microsoft/DacFx/issues/124).

**Comment by dzsquared** [comment]
Now available in preview with Microsoft.Build.Sql - https://github.com/microsoft/DacFx/blob/main/src/Microsoft.Build.Sql/docs/Functionality.md#package-references

**Comment by Adam-S-Daniel** [comment]
![](https://media1.giphy.com/media/pynZagVcYxVUk/giphy.gif)
