### ISSUE TITLE
sqlpackage.exe is recreating non-clustered index and tables that should not

### ISSUE THREAD

**Issue by namangupta211** [microsoft/DacFx#167]
**Problem description:** 

Cx is trying to publish DACPAC sqlpackage to Devops but user created non clustered indexes are being dropped and these indexes are being defined in the DACPAC. cx added arguments in the SQL package trying to avoid indexes to be recreated. the indexes are still being dropped even after cx tried with the new arguments /P: IgnoreIndexOptions=true, /P:IgnoreLockHintsOnIndexes=true, /P:IgnoreFillFactor=true, /P:BlockOnPossibleDataLoss=$(BlockonpPossibleDataLoss), IgnoreIndexPadding = true)
    As a pattern, cx is seeing just the non-cluster indexes being recreated, not the cluster ones.

CX is also seeing now in the logs that tables are being re-built as well, not just indexes and want to know Why it's doing the re-build when nothing was changed?

Has this problem surfaced recently, or the issue has always existed? recently
Were there any changes around the time the issue started (i.e., any application, workload, schema, data or query changes)?  NO
 
**Query:**
"D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\SqlPackage.exe" /Action:Publish /SourceFile:"D:\Agent03\_work\r472\a\drop\source.dacpac" /TargetServerName:"***" /TargetDatabaseName:"****" /TargetUser:"****" /TargetPassword:"********" /p:BlockOnPossibleDataLoss=true /p:IgnoreIndexOptions=True /p:IgnoreLockHintsOnIndexes=True /p:IgnoreFillFactor=True /p:IgnoreIndexPadding=True /TargetTimeout:120

DDL in the DACPAC

CREATE TABLE [CustomerDATA].[PRODUCT_APPLICATION_ACCOUNT]

( 

……

)

go

CREATE UNIQUE NONCLUSTERED INDEX [PRODUCT_APPLICATION_ACCT_PK] ON [CustomerDATA].[PRODUCT_APPLICATION_ACCOUNT]

( 

    [PRODUCT_APPLICATION_ACCOUNT_ID]  ASC

)

go

CREATE UNIQUE NONCLUSTERED INDEX [PRODUCT_APPLICATION_ACCT_USI1] ON [CustomerDATA].[PRODUCT_APPLICATION_ACCOUNT]

( 

    [ACCESS_NUMBER]       ASC,

    [APPLICATION_ACCOUNT_NUMBER],

    [LINE_OF_BUSINESS_CODE],

    [RECORD_TYPE]         ASC

)

go

CREATE CLUSTERED INDEX [PRODUCT_APPLICATION_ACCT_NUSI1] ON [CustomerDATA].[PRODUCT_APPLICATION_ACCOUNT]

( 

    [ETL_DATASET_TYPE]    ASC

)

go

The two Non clustered indexes are being rebuilt.

**Comment by SeenaAugusty** [comment]
This issue was there in a particular dacpac that does not have space for masked function with partial in the column where index is created on that column. The model.xml of this particular dacpac didnot had the space whereas in the dacpac generated using the latest sqlPackage.exe had space returned both from sql server 2022 as well as azure db. Therefore this particular dacpac looked different while publishing that caused the dropping and recreating of indexes and tables.

I tried creating a table without space in partial method of masking function applied to column, created a non clustered index on the same column, and took the dacpac and found that model.xml had space. I used latest sqlpackage.exe of version 16.0.6296.0.
![image](https://user-images.githubusercontent.com/113181575/200240278-d2bc52b1-fd22-412f-8e65-cd905110d3a3.png)
Publishing this dacpac, did not had the issue of dropping and rebuilding the indexes and table
