### ISSUE TITLE
Deprecate old system dacpac packages

### ISSUE THREAD

**Issue by zijchen** [microsoft/DacFx#268]
We now ship system dacpac Nuget packages as separate packages. Old ones have been delisted but existing package references still work.

|Deprecated|Dacpac|New package|
|---|---|---|
|Microsoft.SqlServer.Dacpacs|master|[Microsoft.SqlServer.Dacpacs.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Master)|
|Microsoft.SqlServer.Dacpacs|msdb|[Microsoft.SqlServer.Dacpacs.Msdb](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Msdb)|
|Microsoft.SqlServer.Dacpacs.Azure|master|[Microsoft.SqlServer.Dacpacs.Azure.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Azure.Master)|
|Microsoft.SqlServer.Dacpacs.Synapse|master|[Microsoft.SqlServer.Dacpacs.Synapse.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Synapse.Master)|
||master|[Microsoft.SqlServer.Dacpacs.SynapseServerless.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.SynapseServerless.Master)|

**Comment by lepagea01** [comment]
I'm afraid the new [Microsoft.SqlServer.Dacpacs.Synapse.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Synapse.Master) package is incomplete. For instance, it does not seem to contain any `sys.dm_pdw_...` and `sys.pdw_...` view definitions. I didn't check if other object definitions are missing or if missing objects are all related to PDW. Surprising since the size of the new model.xml file is ~4 times larger than the size of its counterpart in the former _Microsoft.SqlServer.Dacpacs.Synapse_ package.

Database projects referencing the __master__ database (dedicated SQL Pool) no longer build successfully. Workaround for the time being is to stick with the now deprecated package.

**Comment by lepagea01** [comment]
OK, I investigated a little bit further and the new [Microsoft.SqlServer.Dacpacs.Synapse.Master](https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Synapse.Master) package only contains definitions for 51 table valued functions in the __sys__ schema. If the intent here is to replace the now deprecated package, it should contain view definitions in the __INFORMATION_SCHEMA__ schema as well as view and procedure definitions in the __sys__ schema. 251 object definitions total if I'm not mistaken.

**Comment by gfody** [comment]
Microsoft.SqlServer.Dacpacs.Msdb is also incomplete - it's missing sysjobs and all of the [agent srocs](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sql-server-agent-stored-procedures-transact-sql?view=sql-server-ver16)

**Comment by Nathalilly** [comment]
Microsoft.SqlServer.Dacpacs.Msdb I get unresolved references to:
msdb.dbo.backupset
msdb.dbo.log_shipping_primary_databases

**Comment by dzsquared** [comment]
@zijchen - we're good to close this now, right?

**Comment by zijchen** [comment]
Yes please update references to the latest versions posted on nuget.org. If there are any unresolved references errors, feel free to reopen or create a new issue.
