### ISSUE TITLE
DB import fails on 'ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY'

### ISSUE THREAD

**Issue by surekota** [microsoft/DacFx#29]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core: .NET core
- Environment (local platform and source/target platforms): local platform

**Steps to Reproduce:**

1. Have azure sql Db with the feature on ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY
2. Export the DB using sql export into a bacpac
3. Locally import into on-prem/stand alone SQL

Expected behavior - if there are any SQL azure features not applicable for on-prem sqlpackage should handle and let the DB gets imported successfully

Actual behavior - Failing wit the following exception

The import fails with the below error -

Error output was: \r\n *** Error importing database:Could not import package. Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 102, Level 15, State 1, Line 5 Incorrect syntax near 'ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY'. Error SQL72045: Script execution error. The executed script: IF EXISTS (SELECT 1 FROM [master].[dbo].[sysdatabases] WHERE [name] = N'$(DatabaseName)') BEGIN ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = ON; ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = OFF; END

Suggested fix:
IF ( EXISTS  (select * from sys.database_scoped_configurations where name = 'ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY')) 

    BEGIN

    End

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio) - it fails with all the sqlpackage versions and it never worked

**Comment by surekota** [comment]
see ICM - 258531280 for more details

**Comment by kisantia** [comment]
Notes for later:
Had a similar the problem for with OPTIMIZE_FOR_ADHOC_WORKKLOADS. This was fixed in https://sqlbuvsts01/Main/Data%20Tools/_versionControl/changeset/1379071, so those files are a starting point for investigation. 

That was a one-off fix, but since this is a scenario that will be hit by all the new database scoped configurations that get added that aren't supported on previous versions of SQL Server, we need to have a different solution to handle all of these.
