### ISSUE TITLE
sql project template not working on arm

### ISSUE THREAD

**Issue by gfody** [microsoft/DacFx#319]
- SqlPackage or DacFx Version: 162.0.52 (Microsoft.Build.Sql.Templates 0.1.10-preview)
- .NET Framework (Windows-only) or .NET Core: 4.8.1 for ARM64 (KB5028948)
- Environment (local platform and source/target platforms): VS2022 (ARM64) Version 17.7.1, Windows 11 22H2 (OS Build 22621.2134)

**Steps to Reproduce:**

1. File -> New -> Project -> SQL Server Database Project -> (defaults) -> Create
2. Nothing happens

3. I tried upgrading an existing project, it fails to load with the following error messages:
> The 'IntellisensehostingEngine Package' package did not load correctly.

> The specified module could not be found. (Exception from HRESULT: 0x8007007E)

> [ActivityLog.xml](https://github.com/microsoft/DacFx/files/12393111/ActivityLog.xml.txt)

**Did this occur in prior versions?  If not - which version(s) did it work in?**

I'll try the previous versions later and report back

edit - same error even for the current non-preview SSDT. searching the error turns up [this thread](https://learn.microsoft.com/en-us/answers/questions/1190040/sql-server-data-tool-(ssdt)-on-windows-11-parallel) which is resolved as "not supported" and there's a link to [vote to add support](https://developercommunity.visualstudio.com/t/Arm64-support-for-Data-storage-and-proce/10114057) so I suppose this just isn't expected to be working yet

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by GummiGerken** [comment]
Was this issue actually fixed, or just deemed "not supported"? I am getting the same exact error on my machine.

- Apple MacBook Pro M1 Max 
- Windows 11 in Parallels VM
- Microsoft Visual Studio Professional 2022 (ARM 64-bit) Version 17.8.5
- .NET 8

**Comment by dzsquared** [comment]
@GummiGerken - this issue has 2 intertwined components - 
1. support for arm64 Visual Studio is on its way for SSDT and the original SQL projects (https://developercommunity.visualstudio.com/t/Arm64-support-for-Data-storage-and-proce/10114057)
2. the SDK-style SQL projects (Microsoft.Build.Sql), which we focus on in this repository, has a nuget package for the templates (Microsoft.Build.Sql.Templates).  Support for SDK-style SQL projects is available in VS Code and Azure Data Studio, not yet in Visual Studio.  There was a bug the SDK-style projects for version 0.1.10-preview where builds would fail on arm64 machines, this has been fixed in subsequent versions.

If your interest is in getting IDE support for SDK-style SQL projects in Visual Studio, please feel free to let the team know - https://developercommunity.visualstudio.com/t/Use-new-project-file-format-for-sqlproj/480461

**Comment by czb182** [comment]
Regarding #2 I’m kind of surprised there should be a need to ask for this. It’s a gap in functionality that is long overdue.On Jan 23, 2024, at 10:43 AM, Drew Skwiers-Koballa ***@***.***> wrote:﻿
@GummiGerken - this issue has 2 intertwined components -

support for arm64 Visual Studio is on its way for SSDT and the original SQL projects (https://developercommunity.visualstudio.com/t/Arm64-support-for-Data-storage-and-proce/10114057)
the SDK-style SQL projects (Microsoft.Build.Sql), which we focus on in this repository, has a nuget package for the templates (Microsoft.Build.Sql.Templates).  Support for SDK-style SQL projects is available in VS Code and Azure Data Studio, not yet in Visual Studio.  There was a bug the SDK-style projects for version 0.1.10-preview where builds would fail on arm64 machines, this has been fixed in subsequent versions.

If your interest is in getting IDE support for SDK-style SQL projects in Visual Studio, please feel free to let the team know - https://developercommunity.visualstudio.com/t/Use-new-project-file-format-for-sqlproj/480461

**Comment by justintoth** [comment]
This doesn't answer your question in its entirety, but support in ARM for sqlproj files was just released today in the Visual Studio 2022 Preview channel (https://visualstudio.microsoft.com/vs/preview/). I can now open my sqlproj files in Visual Studio 2022 Preview and build the projects.
