### ISSUE TITLE
Export/extract validation error with ISJSON

### ISSUE THREAD

**Issue by zijchen** [microsoft/DacFx#375]
- SqlPackage or DacFx Version: 162.1.167
- .NET Framework (Windows-only) or .NET Core: both
- Environment (local platform and source/target platforms): SQL 2022

**Steps to Reproduce:**

1. Create a database with following schema in SQL 2022:
```tsql
CREATE TABLE tb_json([htmlMetadata] NVARCHAR(MAX))

ALTER TABLE tb_json
ADD CONSTRAINT json_constraint
CHECK ([htmlMetadata] IS NULL OR isjson([htmlMetadata],OBJECT)>0);
```
2. Export will fail with this error
> *** Error extracting database:Validation of the schema model for data package failed.
Error SQL71501: Error validating element [dbo].[json_constraint]: SqlCheckConstraint: [dbo].[json_constraint] has an unresolved reference to object [dbo].[tb_json].[OBJECT].

DacFx is not understanding the `OBJECT` keyword in the ISJSON function, thinking it's a column reference.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by mattshanaman** [comment]
This bug is still present when using sqlpackage.exe version 162.4.92.3.   Is there a newer version coming out that this fix is included in?   I tested this using SSDT projects with compatibility level set to SQL 2022. Additionally, I attempted using Target Platforms SQL Server 2022 and then Microsoft Azure SQL Database to determine if either target platform setting worked correctly.  Visual Studio Enterprise 2022 was updated to version 17.11.5 running on Windows 11.

**Comment by ssreerama** [comment]
@mattshanaman, When you mention testing with an SSDT project, are you utilizing its dacpac/bacpac to test in the [sqlpackage.exe ](https://sqlpackage.exe/?form=MG0AV3)application? This fix is exclusive to SqlPackage; you can test directly by extracting/exporting your database from the command prompt or by using the DacFx NuGets. The SSDT 17.12 Preview 4 version includes this fix, whereas earlier versions still employ DacFx 162.3.xxx.

**Comment by mattshanaman** [comment]
Thank for you the additional information @ssreerama!  I will test that...
