### ISSUE TITLE
Building a project under a folder with escaped spaces skips scripts

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/DacFx#408]
- SqlPackage or DacFx Version: [Build SDK 0.1.14-preview](https://www.nuget.org/packages/Microsoft.Build.Sql/0.1.14-preview)
- .NET Framework (Windows-only) or .NET Core: .NET Core
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Unzip attached demo folder
2. Run dotnet build in both of the contained folders with the projects (which are the same aside from the name)

For the NoSpaces one it builds as expected (verified through Model.xml that objects are included).

For the With Spaces one it seemingly builds fine, but then the Model.xml doesn't have any of the objects - so it seems like it's completely skipping over them.

[Demo.zip](https://github.com/microsoft/DacFx/files/14251507/Demo.zip)

**Comment by dzsquared** [comment]
A related but worse version of this is building a project in a folder with escaped spaces in 0.2.0-preview results in a failed build

/usr/local/share/dotnet/sdk/8.0.303/Microsoft.Common.CurrentVersion.targets(1248,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/drewsk/Documents/CodeRepos/dzsquared/App%20Demo/SQLDatabase/MessagesDB.sqlproj]

**Comment by zijchen** [comment]
This might be related to a widely reported issue with .NET itself - https://github.com/dotnet/msbuild/issues/2178

The symptoms I observe with Microsoft.Build.Sql are:
* <= 0.1.14-preview: globbing patterns (any) don't work. Only workaround is to include each file like old-style sqlproj.
* \> 0.1.14-preview: `error NETSDK1004: Assets file '...\With Escaped Spaces\obj\project.assets.json' not found.` Likely due to direct reference to Microsoft.NET.Sdk.targets introduced in 0.1.15-preview. This error is exactly same as the dotnet one, from the comments it seems to be coming from Nuget.

I will do more investigation, but the core problem seems to reside within the .NET/Nuget.

**Comment by zijchen** [comment]
The issue lies in .NET with no known workarounds at this time. Please avoid using escaped spaces in the project path.
